apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: dev
  labels:
    app: mariadb-svc
spec:
  ports:
    - name: mysql 
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb