apiVersion: v1
kind: Service
metadata:
  name: ems-app-svc
  namespace: prod
  labels:
    app: ems-app-svc
spec:
  type: NodePort
  selector:
    app: ems-app
  ports:
    - name: http 
      port: 80
      targetPort: 8080
